version: "{branch}-ci-{build}"
os: Visual Studio 2013

on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  BOOST_ROOT: C:\Libraries\boost_1_58_0
#  BOOST_INCLUDEDIR: C:\Libraries\boost_1_59_0\boost
  platform: x86
  QTDIR: C:\Qt\5.7\msvc2013 
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_58_0\lib32-msvc-12.0

install:
- git submodule init
- git submodule update
- cmd: call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
- cmd: set PATH=%PATH%;%QTDIR%\bin
- cmd: DIR %BOOST_LIBRARYDIR%

build_script:
- cmd: qmake 
- cmd: nmake /NOLOGO

after_build:
- cmd: package_script.bat

artifacts:
  - path: cenniki.7z
    name: cenniki.7z

deploy:
  description: "# Cenniki

##Version %APPVEYOR_REPO_TAG_NAME% arch x86 
"
  provider: GitHub
  auth_token:
    secure: ogmv8nz5XumGTJew9jWXUvPQ8U4J9t4z7WcAIG+xYHrbqnenBO5x0NUZvCMitga6 
  artifact: cenniki.7z 
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

