version: "{branch}-ci-{build}"
os: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
#  BOOST_INCLUDEDIR: C:\Libraries\boost_1_59_0\boost
  platform: x86
  QTDIR: C:\Qt\5.7\msvc2015 
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

install:
- git submodule init
- git submodule update
- cmd: call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
- cmd: set PATH=%PATH%;%QTDIR%\bin
#- cmd: qmake -v
#- cmd: dir %BOOST_ROOT%
#- cmd: dir %BOOST_INCLUDEDIR%

build_script:
- cmd: dir %BOOST_LIBRARYDIR%
- cmd: qmake 
#"INCLUDEPATH += %BOOST_ROOT%  LIBS += %BOOST_LIBRARYDIR%/libboost_serialization-vc140-mt-1_59.lib"
- cmd: nmake /NOLOGO 

#test_script:

#branches:
#  only:
#  - master

